### ISSUE TITLE
I select one day, but the date i get is previous day

### ISSUE THREAD

**Issue by Chihpin** [kovpas/PMCalendar#42]
China Beijing +08:00

![image](https://cloud.githubusercontent.com/assets/6008594/8449928/6526a952-2008-11e5-9822-c1a176e86bf3.png)
![image](https://cloud.githubusercontent.com/assets/6008594/8450003/09a9b708-2009-11e5-9441-5feca0e19070.png)

**Comment by kovpas** [comment]
Sorry, this lib is not supported anymore. Pull requests are welcome, though :)
