### ISSUE TITLE
How to dismiss the calendar once i selected the date

### ISSUE THREAD

**Issue by Jiyas** [kovpas/PMCalendar#45]
i cant able to dismiss the calendar view once i selected the date from that

**Comment by kovpas** [comment]
@Jiyas there's a delegate method which is invoked upon date selection:

```
- (void)calendarController:(PMCalendarController *)calendarController didChangePeriod:(PMPeriod *)newPeriod;
```

**Comment by Jiyas** [comment]
Thank You for your Response ,Here is my code ->
- (void)calendarController:(PMCalendarController *)calendarController
  didChangePeriod:(PMPeriod *)newPeriod
  {
  if(tfTemp==tfFromDate)
  
  {
     tfFromDate.text=[NSString stringWithFormat:@"%@ ", [newPeriod.
  startDate dateStringWithFormat:@"dd-MM-yyyy"]];
     [Shareinfo sharedMySingleton].tripStartDate=newPeriod.startDate;
     [self.pmCC calendarControllerDidDismissCalendar:NO];
  }
  else
  {
     tfToDate.text=[NSString stringWithFormat:@"%@ ", [newPeriod.endDate
  dateStringWithFormat:@"dd-MM-yyyy"]];
     [Shareinfo sharedMySingleton].tripEndDate=newPeriod.endDate;
  
  ```
    [self.pmCC calendarControllerDidDismissCalendar:NO];
  ```
  
  }
  }

On that,  'if' condition is starting date and 'else' is ending date.Hence i
used *\* [self.pmCC dismissCalendarAnimated:NO];*\* in both to dismiss the
view once the user selected the date.But its not working .Calendar view is
not appearing.

**Comment by kovpas** [comment]
To be honest, it's really hard to say what's wrong with your code. It is very likely that something is wrong with the PMCalendar too - it's not maintained anymore and something could be broken as well.

**Comment by Jiyas** [comment]
After commenting the line*\* [self calendarController:pmCC didChangePeriod:pmCC.period];**
in*\* -(void) showCalendar:(UITextField _) sender_\* .Its working Perfectly :)

**Comment by kovpas** [comment]
Glad you fixed it! :)
